version: '3.8'

services:
  app:
    build: .
    volumes:
      - ./data:/data
    ports:
      - "8000:8000" 
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

volumes:
  app_data: